// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Keyless]
public partial class Product
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("Category_ID")]
    public int CategoryId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Description { get; set; }

    public int? Price { get; set; }

    [Column("Image_path")]
    [StringLength(100)]
    [Unicode(false)]
    public string ImagePath { get; set; }
}