// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Product
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public int? Price { get; set; }

    [Column("Category_ID")]
    public int? CategoryId { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
   
    public virtual Category Category{ get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}